" .vimrc by Daniel Ohlsson
" To reload the vimrc while editing it use :so %


" Some regular stuff
syntax on
set autoindent
set tabstop=4
set ignorecase
set hlsearch

" Some maps for tab commands
map <Tab> :tabn<CR>
map <S-Tab> :tabN<CR>

" Rust syntax-highlighting
au BufNewFile,BufRead *.rs set filetype=rust
