" .vimrc by Daniel Ohlsson
" To reload the vimrc while editing it use :so %

" plugin management with vim-plug
try
	call plug#begin()
	" Plug 'https://github.com/ctrlpvim/ctrlp.vim'
	Plug 'https://github.com/ternjs/tern_for_vim'
	" Update vim plz
	" Plug 'https://github.com/Valloric/YouCompleteMe'
	Plug 'https://github.com/pangloss/vim-javascript'
	Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
	Plug 'junegunn/fzf.vim'
	Plug 'https://github.com/tpope/vim-fugitive'
	Plug 'https://github.com/scrooloose/nerdtree'
	Plug 'https://github.com/jistr/vim-nerdtree-tabs'
	Plug 'https://github.com/vim-airline/vim-airline'
	Plug 'https://github.com/vim-airline/vim-airline-themes'
	call plug#end()
catch
endtry

" Disable scratchpad preview for YCM
set completeopt-=preview

" Some regular stuff
syntax on
colorscheme mycolors
set autoindent
set tabstop=4
set ignorecase
set incsearch
set hlsearch
set tabpagemax=100
set showcmd
"set cursorline		is buggy Currently makes scrolling lag
"set cursorcolumn

" Autocomplete code
set omnifunc=syntaxcomplete#Complete

" Autocompletion more like bash
set wildmode=longest,list,full
set wildmenu

" Do not write new inode when saving file
set backupcopy=yes

" Check if working file is updated when entering that buffer
au FocusGained,BufEnter * :silent! checktime

" Some maps for tab commands
map <Tab> :tabn<CR>
map <S-Tab> :tabN<CR>
map <Space> @@

" Move vertically by visual line
nnoremap j gj
nnoremap k gk

" Disable arrow-keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Tern stuff
let g:tern_map_keys=1
let g:tern_show_argument_hints='on_hold'

" Fzf bindings
nmap <leader>f :Files<CR>
nmap <leader>gc :Commits<CR>
nmap <leader>gf :GFiles<CR>
nmap <leader>gs :GFiles?<CR>
nmap <leader>h :History<CR>

" fugitive.vim bindings
nmap <leader>gb :Gblame<CR>

" NERDTree bindings
nmap <leader>t :NERDTreeTabsToggle<CR>

" Airline
let g:airline_powerline_fonts = 1

" Javascript specific indentation
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 expandtab
autocmd BufNewFile,BufRead *.json set ft=javascript

" Python specific indentation
autocmd FileType python setlocal tabstop=4 expandtab
au BufEnter *.py set ft=python

autocmd FileType yaml setlocal shiftwidth=2 tabstop=2 expandtab
autocmd FileType html setlocal shiftwidth=2 tabstop=2 expandtab

" Get highlighting group under cursor
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
						\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
						\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
