#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='\[\a\]\[\033[01;32m\]\u@\h \[\033[01;34m\]\W \$ \[\033[00m\]'

# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias less='less -Ri'
alias mkdir='mkdir -pv'
alias i3lock='i3lock -c 000000'

# Shell variables
export TERMINAL=urxvt
export EDITOR=vim
export PATH=$PATH:/sbin/:/usr/sbin/
export PATH=$PATH:$HOME/.bin

# Unlimited bash history
export HISTFILESIZE=
export HISTSIZE=

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	  elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi
